import {test,expect} from '@playwright/test'

test.beforeEach(async({page})=>{await page.route('**/api/targets',route=>route.fulfill({json:[]}));await page.route('**/api/targets/test-status',route=>route.fulfill({json:[]}));await page.route('**/api/test-runs',route=>route.fulfill({json:[]}))})

test('opens the three primary DICOM workflows',async({page})=>{await page.goto('/');await expect(page.getByRole('heading',{name:'Übersicht'})).toBeVisible();await page.getByRole('button',{name:'Jetzt testen'}).click();await expect(page.getByRole('heading',{name:'Worklist',exact:true})).toBeVisible();await page.getByRole('link',{name:'PACS Store',exact:true}).click();await expect(page.getByRole('heading',{name:'PACS Store',exact:true})).toBeVisible();await page.getByRole('link',{name:'Übersicht',exact:true}).click();await page.getByRole('button',{name:'Studien suchen'}).click();await expect(page.getByRole('heading',{name:'PACS-Suche',exact:true})).toBeVisible()})
test('header links provide help and history without pretending to have accounts or notifications',async({page})=>{await page.goto('/worklist');await expect(page.getByText('Ohne Anmeldung')).toBeVisible();await expect(page.getByText('Admin',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Benachrichtigungen'})).toHaveCount(0);await page.getByRole('link',{name:'Hilfe öffnen'}).click();await expect(page.getByRole('heading',{name:'Hilfe & Schnellstart'})).toBeVisible();await expect(page.getByText(/keine Benutzeranmeldung/)).toBeVisible();await page.getByRole('link',{name:'Test-Historie öffnen'}).click();await expect(page.getByRole('heading',{name:'Test-Historie'})).toBeVisible();await page.getByRole('link',{name:'Zur Übersicht'}).click();await expect(page.getByRole('heading',{name:'Übersicht'})).toBeVisible()})
test('help and security notice remain accessible on a phone',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.getByText('Ohne Anmeldung')).toBeVisible();await page.getByRole('link',{name:'Hilfe öffnen'}).click();await expect(page.getByRole('heading',{name:'Hilfe & Schnellstart'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)})

test('worklist zero-result diagnosis offers broad query',async({page})=>{await page.route('**/api/dicom/mwl',route=>route.fulfill({json:{success:true,status:'0x0000',duration_ms:22,count:0,entries:[],active_filters:{station_ae:'CT01'}}}));await page.goto('/worklist');for(const [label,value] of [['Host','127.0.0.1'],['Called AE','MWL'],['Station AE','CT01']])await page.getByLabel(label).fill(value);await page.getByRole('button',{name:'Worklist abfragen'}).click();await expect(page.getByText('Keine Worklist-Einträge gefunden')).toBeVisible();await expect(page.getByRole('button',{name:'Broad Query',exact:true}).last()).toBeVisible()})

test('store success shows generated UIDs',async({page})=>{await page.route('**/api/dicom/store/generated',route=>route.fulfill({json:{success:true,status:'0x0000',duration_ms:42,study_instance_uid:'1.2.3',series_instance_uid:'1.2.3.4',sop_instance_uid:'1.2.3.4.5',sop_class:'CT Image Storage',transfer_syntax:'Explicit VR Little Endian'}}));await page.goto('/store');await page.getByLabel('Host').fill('127.0.0.1');await page.getByLabel('Called AE').fill('PACS');await page.getByRole('button',{name:'C-STORE senden'}).click();await expect(page.getByText('1.2.3',{exact:true})).toBeVisible();await expect(page.getByText('0x0000',{exact:true}).first()).toBeVisible()})

test('manual test endpoint can be saved as target',async({page})=>{let saved=false;await page.route('**/api/dicom/store/generated',route=>route.fulfill({json:{success:true,status:'0x0000',duration_ms:20}}));await page.route('**/api/targets',async route=>{if(route.request().method()==='POST'){saved=true;return route.fulfill({status:201,json:{id:1,...route.request().postDataJSON(),created_at:'2026-09-10',updated_at:'2026-09-10'}})}return route.fulfill({json:[]})});page.on('dialog',dialog=>dialog.accept('Test PACS'));await page.goto('/store');await page.getByLabel('Host').fill('127.0.0.1');await page.getByLabel('Called AE').fill('PACS');await page.getByRole('button',{name:'C-STORE senden'}).click();await page.getByRole('button',{name:'Als Ziel speichern'}).click();await expect.poll(()=>saved).toBe(true)})

test('history opens stored technical result',async({page})=>{await page.route('**/api/test-runs/42',route=>route.fulfill({json:{id:42,test_type:'mwl_find',target_id:null,manual_target_json:{host:'127.0.0.1',port:104,called_ae:'MWL',calling_ae:'DCMSIM'},started_at:'2026-09-10T20:00:00Z',duration_ms:31,success:true,status:'0x0000',result_json:{success:true,status:'0x0000',count:3,duration_ms:31}}}));await page.goto('/history/42');await expect(page.getByRole('heading',{name:/Worklist/})).toBeVisible();await page.getByText('Gespeicherte Request-/Response-Daten').click();await expect(page.getByText(/"count": 3/)).toBeVisible()})
test('history detail preserves the endpoint used by a saved target',async({page})=>{await page.route('**/api/test-runs/43',route=>route.fulfill({json:{id:43,test_type:'dicom_echo',target_id:1,manual_target_json:null,target_snapshot_json:{name:'PACS Alt',host:'192.0.2.1',port:11112,called_ae:'PACSOLD',calling_ae:'DCMSIM'},started_at:'2026-09-12T10:00:00Z',duration_ms:31,success:true,status:'0x0000',result_json:{success:true,status:'0x0000',duration_ms:31}}}));await page.goto('/history/43');await expect(page.getByText('PACS Alt')).toBeVisible();await expect(page.getByText('192.0.2.1',{exact:true})).toBeVisible();await expect(page.getByText('PACSOLD',{exact:true})).toBeVisible()})

test('history filters on the server and exports the selection',async({page})=>{const run={id:7,test_type:'dicom_echo',target_id:null,manual_target_json:{host:'10.20.30.40',port:104,called_ae:'PACS',calling_ae:'DCMSIM'},started_at:'2026-09-12T10:00:00Z',duration_ms:12,success:false,status:'DICOM_TIMEOUT',result_json:{success:false,code:'DICOM_TIMEOUT',duration_ms:12}};await page.route('**/api/test-runs/search*',route=>route.fulfill({json:{items:[run],total:1,limit:50,offset:0}}));await page.route('**/api/test-runs/export.csv*',route=>route.fulfill({contentType:'text/csv',body:'Zeitpunkt;Testtyp;Status\n2026-09-12;dicom_echo;DICOM_TIMEOUT'}));await page.goto('/history');await page.getByLabel('Status').selectOption('false');await expect(page).toHaveURL(/\/history$/);await expect(page.getByText('DICOM_TIMEOUT')).toBeVisible();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'CSV exportieren'}).click();const download=await downloadPromise;expect(download.suggestedFilename()).toMatch(/^dcmsim-history-.*\.csv$/)})

test('store displays presentation context rejection',async({page})=>{await page.route('**/api/dicom/store/generated',route=>route.fulfill({json:{success:false,code:'DICOM_NO_PRESENTATION_CONTEXT',message:'No acceptable presentation context',duration_ms:18,details:{sop_class:'CT Image Storage'}}}));await page.goto('/store');await page.getByLabel('Host').fill('127.0.0.1');await page.getByLabel('Called AE').fill('PACS');await page.getByRole('button',{name:'C-STORE senden'}).click();await expect(page.locator('.result-summary')).toContainText('No acceptable presentation context');await expect(page.getByText('DICOM_NO_PRESENTATION_CONTEXT').first()).toBeVisible()})

test('mobile navigation opens and closes after selecting a page',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');const menu=page.getByRole('button',{name:'Navigation öffnen'});await expect(menu).toBeVisible();await menu.click();await expect(page.getByRole('navigation',{name:'Hauptnavigation'})).toBeInViewport();await page.getByRole('link',{name:'Worklist',exact:true}).click();await expect(page.getByRole('heading',{name:'Worklist',exact:true})).toBeVisible();await expect(page.locator('.sidebar')).not.toHaveClass(/sidebar--open/)})

test('creates a modality profile that remains after reload',async({page})=>{const target={id:1,name:'JiveX Produktion',host:'127.0.0.1',mwl_enabled:true,mwl_port:104,mwl_called_ae:'JIVEXWL',store_enabled:true,store_port:104,store_called_ae:'JIVEX',default_calling_ae:'DCMSIM',created_at:'',updated_at:''};let profiles:unknown[]=[];await page.route('**/api/targets',route=>route.fulfill({json:[target]}));await page.route('**/api/modality-profiles',async route=>{if(route.request().method()==='POST'){const value={id:4,...route.request().postDataJSON(),created_at:'2026-09-11',updated_at:'2026-09-11'};profiles=[value];return route.fulfill({status:201,json:value})}return route.fulfill({json:profiles})});await page.goto('/modalities');await page.getByRole('button',{name:'Neue Modalität'}).click();await page.getByLabel('Name').fill('Aplio 300 – Sono 2');await page.getByLabel('Modalität',{exact:true}).selectOption('US');await page.getByLabel('Calling AE').fill('APLIO02');await page.getByLabel('Worklist Target').selectOption('1');await page.getByLabel('Store Target').selectOption('1');await page.getByRole('button',{name:'Speichern'}).click();await expect(page.getByText('Aplio 300 – Sono 2')).toBeVisible();await page.reload();await expect(page.getByText('Aplio 300 – Sono 2')).toBeVisible()})

test('modality check displays worklist, store and overall result',async({page})=>{const target={id:1,name:'JiveX Produktion',host:'127.0.0.1',mwl_enabled:true,mwl_port:104,mwl_called_ae:'JIVEXWL',store_enabled:true,store_port:104,store_called_ae:'JIVEX',default_calling_ae:'DCMSIM',created_at:'',updated_at:''};const profile={id:4,name:'Aplio 300 – Sono 2',description:null,modality:'US',calling_ae:'APLIO02',mwl_enabled:true,mwl_target_id:1,store_enabled:true,store_target_id:1,created_at:'',updated_at:''};await page.route('**/api/targets',route=>route.fulfill({json:[target]}));await page.route('**/api/modality-profiles',route=>route.fulfill({json:[profile]}));await page.route('**/api/modality-profiles/4/check',route=>route.fulfill({json:{success:true,status:'PASS',overall:'success',duration_ms:42,profile_id:4,profile_name:profile.name,modality:'US',calling_ae:'APLIO02',run_id:10,worklist:{success:true,status:'0x0000',duration_ms:18,count:14,association:true,query:{station_ae:'APLIO02'}},store:{success:true,status:'0x0000',duration_ms:24,association:true,sop_class:'Ultrasound Image Storage',transfer_syntax:'Explicit VR Little Endian'}}}));await page.goto('/modalities');await page.getByRole('button',{name:'Modalität prüfen'}).click();await expect(page.getByText('Overall PASS')).toBeVisible();await expect(page.getByText('Ultrasound Image Storage')).toBeVisible();await expect(page.getByText('14',{exact:true})).toBeVisible()})

test('PACS study query displays studies and technical response',async({page})=>{await page.route('**/api/dicom/studies',route=>route.fulfill({json:{success:true,status:'0x0000',duration_ms:20,count:1,entries:[{patient_name:'DCMSIM^QUERY',patient_id:'DCMSIM-Q1',accession_number:'QR-1',study_date:'20260911',study_time:'101500',study_description:'SYNTHETIC STUDY',study_instance_uid:'1.2.826.1',modalities:'CT',series_count:2,instance_count:42,dataset:[{tag:'(0020,000D)',name:'Study Instance UID',vr:'UI',value:'1.2.826.1'}]}]}}));await page.goto('/pacs-query');await page.getByLabel('Host').fill('127.0.0.1');await page.getByLabel('Called AE').fill('PACSQR');await page.getByRole('button',{name:'Studien suchen'}).click();await expect(page.getByText('SYNTHETIC STUDY')).toBeVisible();await page.getByText('SYNTHETIC STUDY').click();await expect(page.getByRole('dialog',{name:'DICOM-Studienantwort'})).toContainText('Study Instance UID')})

test('saved local defaults are applied to workflows and compact tables',async({page})=>{await page.goto('/settings');const ae=page.getByLabel('Default Calling AE');await ae.fill('LOCAL_AET');await page.getByRole('button',{name:'Einstellungen speichern'}).click();await page.getByRole('link',{name:'Worklist',exact:true}).click();await expect(page.getByLabel('Calling AE')).toHaveValue('LOCAL_AET');await page.getByRole('link',{name:'Einstellungen',exact:true}).click();await page.getByRole('button',{name:'UI'}).click();await page.getByText('Kompakte Tabellenansicht',{exact:true}).click();await page.getByRole('button',{name:'Einstellungen speichern'}).click();await expect(page.locator('html')).toHaveClass(/compact-tables/)})

test('settings show effective server values without editable placeholders',async({page})=>{await page.route('**/api/settings/runtime',route=>route.fulfill({json:{connect_timeout:7.5,association_timeout:12,dimse_timeout:30,log_level:'WARNING'}}));await page.goto('/settings');await expect(page.getByText('7.5 s')).toBeVisible();await expect(page.getByText('12 s')).toBeVisible();await expect(page.getByText('30 s')).toBeVisible();await expect(page.getByLabel('Connect Timeout (Sekunden)')).toHaveCount(0);await page.getByRole('button',{name:'Logging'}).click();await expect(page.getByText('WARNING')).toBeVisible();await expect(page.getByRole('button',{name:'Einstellungen speichern'})).toHaveCount(0)})

test('dashboard shows measured target status instead of assuming availability',async({page})=>{const target={id:1,name:'PACS Archiv',host:'127.0.0.1',mwl_enabled:false,mwl_port:null,mwl_called_ae:null,store_enabled:true,store_port:104,store_called_ae:'PACS',qr_enabled:false,qr_port:null,qr_called_ae:null,default_calling_ae:'DCMSIM',created_at:'',updated_at:''};await page.route('**/api/targets',route=>route.fulfill({json:[target]}));await page.route('**/api/targets/test-status',route=>route.fulfill({json:[{target_id:1,run_id:9,test_type:'dicom_echo',started_at:'2026-09-12T10:00:00Z',duration_ms:20,success:false,status:'DICOM_TIMEOUT',configuration_state:'current'}]}));await page.goto('/');const targetRow=page.getByText('PACS Archiv').locator('xpath=ancestor::tr');await expect(targetRow).toContainText('Fehlgeschlagen');await expect(targetRow).not.toContainText('Konfiguriert')})
test('changed target configuration requires a new test',async({page})=>{const target={id:1,name:'PACS Archiv',host:'127.0.0.1',mwl_enabled:false,store_enabled:true,store_port:104,store_called_ae:'PACS',qr_enabled:false,default_calling_ae:'DCMSIM',created_at:'',updated_at:''};await page.route('**/api/targets',route=>route.fulfill({json:[target]}));await page.route('**/api/targets/test-status',route=>route.fulfill({json:[{target_id:1,run_id:9,test_type:'dicom_echo',started_at:'2026-09-12T10:00:00Z',duration_ms:20,success:true,status:'0x0000',configuration_state:'changed'}]}));await page.goto('/targets');const targetRow=page.getByText('PACS Archiv').locator('xpath=ancestor::tr');await expect(targetRow).toContainText('Erneut prüfen');await expect(targetRow).not.toContainText('Erfolgreich')})
