import {test,expect} from '@playwright/test'

test.beforeEach(async({page})=>{await page.route('**/api/targets',route=>route.fulfill({json:[]}));await page.route('**/api/test-runs',route=>route.fulfill({json:[]}))})

test('opens the two primary DICOM workflows',async({page})=>{await page.goto('/');await expect(page.getByRole('heading',{name:'Übersicht'})).toBeVisible();await page.getByRole('button',{name:'Jetzt testen'}).click();await expect(page.getByRole('heading',{name:'Worklist',exact:true})).toBeVisible();await page.getByRole('link',{name:'PACS Store',exact:true}).click();await expect(page.getByRole('heading',{name:'PACS Store',exact:true})).toBeVisible()})

test('worklist zero-result diagnosis offers broad query',async({page})=>{await page.route('**/api/dicom/mwl',route=>route.fulfill({json:{success:true,status:'0x0000',duration_ms:22,count:0,entries:[],active_filters:{station_ae:'CT01'}}}));await page.goto('/worklist');for(const [label,value] of [['Host','127.0.0.1'],['Called AE','MWL'],['Station AE','CT01']])await page.getByLabel(label).fill(value);await page.getByRole('button',{name:'Worklist abfragen'}).click();await expect(page.getByText('Keine Worklist-Einträge gefunden')).toBeVisible();await expect(page.getByRole('button',{name:'Broad Query',exact:true}).last()).toBeVisible()})

test('store success shows generated UIDs',async({page})=>{await page.route('**/api/dicom/store/generated',route=>route.fulfill({json:{success:true,status:'0x0000',duration_ms:42,study_instance_uid:'1.2.3',series_instance_uid:'1.2.3.4',sop_instance_uid:'1.2.3.4.5',sop_class:'CT Image Storage',transfer_syntax:'Explicit VR Little Endian'}}));await page.goto('/store');await page.getByLabel('Host').fill('127.0.0.1');await page.getByLabel('Called AE').fill('PACS');await page.getByRole('button',{name:'C-STORE senden'}).click();await expect(page.getByText('1.2.3',{exact:true})).toBeVisible();await expect(page.getByText('0x0000',{exact:true}).first()).toBeVisible()})

test('manual test endpoint can be saved as target',async({page})=>{let saved=false;await page.route('**/api/dicom/store/generated',route=>route.fulfill({json:{success:true,status:'0x0000',duration_ms:20}}));await page.route('**/api/targets',async route=>{if(route.request().method()==='POST'){saved=true;return route.fulfill({status:201,json:{id:1,...route.request().postDataJSON(),created_at:'2026-09-10',updated_at:'2026-09-10'}})}return route.fulfill({json:[]})});page.on('dialog',dialog=>dialog.accept('Test PACS'));await page.goto('/store');await page.getByLabel('Host').fill('127.0.0.1');await page.getByLabel('Called AE').fill('PACS');await page.getByRole('button',{name:'C-STORE senden'}).click();await page.getByRole('button',{name:'Als Ziel speichern'}).click();await expect.poll(()=>saved).toBe(true)})

test('history opens stored technical result',async({page})=>{await page.route('**/api/test-runs/42',route=>route.fulfill({json:{id:42,test_type:'mwl_find',target_id:null,manual_target_json:{host:'127.0.0.1',port:104,called_ae:'MWL',calling_ae:'DCMSIM'},started_at:'2026-09-10T20:00:00Z',duration_ms:31,success:true,status:'0x0000',result_json:{success:true,status:'0x0000',count:3,duration_ms:31}}}));await page.goto('/history/42');await expect(page.getByRole('heading',{name:/Worklist/})).toBeVisible();await page.getByText('Gespeicherte Request-/Response-Daten').click();await expect(page.getByText(/"count": 3/)).toBeVisible()})

test('store displays presentation context rejection',async({page})=>{await page.route('**/api/dicom/store/generated',route=>route.fulfill({json:{success:false,code:'DICOM_NO_PRESENTATION_CONTEXT',message:'No acceptable presentation context',duration_ms:18,details:{sop_class:'CT Image Storage'}}}));await page.goto('/store');await page.getByLabel('Host').fill('127.0.0.1');await page.getByLabel('Called AE').fill('PACS');await page.getByRole('button',{name:'C-STORE senden'}).click();await expect(page.locator('.result-summary')).toContainText('No acceptable presentation context');await expect(page.getByText('DICOM_NO_PRESENTATION_CONTEXT').first()).toBeVisible()})

test('mobile navigation opens and closes after selecting a page',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');const menu=page.getByRole('button',{name:'Navigation öffnen'});await expect(menu).toBeVisible();await menu.click();await expect(page.getByRole('navigation',{name:'Hauptnavigation'})).toBeInViewport();await page.getByRole('link',{name:'Worklist',exact:true}).click();await expect(page.getByRole('heading',{name:'Worklist',exact:true})).toBeVisible();await expect(page.locator('.sidebar')).not.toHaveClass(/sidebar--open/)})
