import {AlertTriangle,CheckCircle2,ClipboardList,Database,XCircle} from 'lucide-react'
import {Link} from 'react-router-dom'
import {ModalityCheckResult,ModalityServiceResult} from '../../api/client'
import {Button} from '../ui/Button'
import {CollapsiblePanel} from '../ui/Disclosure'
import {AlertBox} from '../ui/Feedback'
import {KeyValueList} from '../ui/KeyValueList'
import {StatusBadge} from '../ui/Status'

function ServiceResult({title,result,kind}:{title:string;result:ModalityServiceResult;kind:'worklist'|'store'}){if(result.skipped)return <article className="check-service"><div className="check-service__title"><strong>{title}</strong><StatusBadge>Nicht konfiguriert</StatusBadge></div></article>;const Icon=result.success?CheckCircle2:XCircle;return <article className={`check-service check-service--${result.success?'success':'error'}`}><div className="check-service__title"><span><Icon size={21}/><strong>{title}</strong></span><StatusBadge tone={result.success?'success':'error'}>{result.success?'PASS':'FAIL'}</StatusBadge></div><KeyValueList items={kind==='worklist'?[{label:'Association',value:result.association?'PASS':'FAIL'},{label:'C-FIND',value:result.status??result.code??'—',mono:true},{label:'Einträge',value:result.count??'—'},{label:'Station AE',value:result.query?.station_ae??'—',mono:true}]:[{label:'Association',value:result.association?'PASS':'FAIL'},{label:'SOP Class',value:result.sop_class??'—'},{label:'Transfer Syntax',value:result.transfer_syntax??'—'},{label:'C-STORE',value:result.status??result.code??'—',mono:true}]}/>{result.diagnostic_retry&&<AlertBox tone={result.diagnostic_retry.success?'info':'warning'} title="Diagnose ohne Station AE">{result.diagnostic_retry.success?`${result.diagnostic_retry.count??0} Einträge ohne Station-AE-Filter gefunden.`:result.diagnostic_retry.message??'Diagnoseabfrage fehlgeschlagen.'}</AlertBox>}{result.fallback_secondary_capture&&<AlertBox tone="info">Für diese Modalität wurde transparent Secondary Capture als Testobjekt verwendet.</AlertBox>}{!result.success&&<p className="check-error"><span className="mono">{result.code??result.status}</span> · {result.message??'Technischer Teiltest fehlgeschlagen.'}</p>}</article>}

export function ModalityCheckResultPanel({result,showHistoryLink=true}:{result:ModalityCheckResult;showHistoryLink?:boolean}){const success=result.overall==='success';return <div className="modality-check-result"><div className={`check-overall check-overall--${success?'success':'error'}`}>{success?<CheckCircle2 size={30}/>:<AlertTriangle size={30}/>}<div><strong>{result.profile_name}</strong><span>{result.modality} · Calling AE <span className="mono">{result.calling_ae}</span></span></div><StatusBadge tone={success?'success':'error'}>Overall {success?'PASS':'FAIL'}</StatusBadge></div><div className="check-services"><ServiceResult title="Worklist" kind="worklist" result={result.worklist}/><ServiceResult title="PACS Store" kind="store" result={result.store}/></div><CollapsiblePanel title="Technische Details"><pre className="mono">{JSON.stringify(result,null,2)}</pre></CollapsiblePanel>{showHistoryLink&&result.run_id&&<div className="form-actions"><Link to={`/history/${result.run_id}`}><Button variant="outline" icon={<ClipboardList size={16}/>}>Historieneintrag öffnen</Button></Link><span className="check-duration"><Database size={15}/>{result.duration_ms} ms</span></div>}</div>}
