import {DicomEndpoint,Endpoint,Target} from '../../api/client'
import {FormField,NumberInput,Select,TextInput} from '../ui/Form'

export function TargetSelector({value,onChange,targets,endpoints=[],service,compact=false}:{value:Endpoint;onChange:(value:Endpoint)=>void;targets:Target[];endpoints?:DicomEndpoint[];service:'mwl'|'store'|'qr';compact?:boolean}){
 const endpointService={mwl:'MWL',store:'STORE',qr:'QR'}[service]
 const select=(selection:string)=>{
  if(selection.startsWith('endpoint:')){const endpoint=endpoints.find(item=>item.id===Number(selection.slice(9)));return endpoint&&onChange({host:endpoint.host,port:endpoint.port,called_ae:endpoint.called_ae,calling_ae:value.calling_ae,target_id:null})}
  const target=targets.find(item=>item.id===Number(selection));if(!target)return onChange({...value,target_id:null});const port=service==='mwl'?target.mwl_port:service==='store'?target.store_port:target.qr_port;const called=service==='mwl'?target.mwl_called_ae:service==='store'?target.store_called_ae:target.qr_called_ae;onChange({host:target.host,port:port??104,called_ae:called??'',calling_ae:target.default_calling_ae,target_id:target.id})
 }
 const enabled=(target:Target)=>service==='mwl'?target.mwl_enabled:service==='store'?target.store_enabled:target.qr_enabled
 return <div className={compact?'target-fields target-fields--compact':'target-fields'}><FormField label="Ziel" htmlFor={`${service}-target`} className="span-all"><Select id={`${service}-target`} value={value.target_id??''} onChange={event=>select(event.target.value)}><option value="">Manuelle Eingabe</option>{endpoints.filter(item=>item.service===endpointService).map(item=><option value={`endpoint:${item.id}`} key={`endpoint:${item.id}`}>{item.name} · {item.host}:{item.port}</option>)}{targets.filter(enabled).map(target=><option value={target.id} key={target.id}>{target.name} (Legacy)</option>)}</Select></FormField><FormField label="Host" htmlFor={`${service}-host`}><TextInput id={`${service}-host`} className="mono" required value={value.host} placeholder="10.10.10.50" onChange={event=>onChange({...value,host:event.target.value,target_id:null})}/></FormField><FormField label="Port" htmlFor={`${service}-port`}><NumberInput id={`${service}-port`} className="mono" min={1} max={65535} required value={value.port} onChange={event=>onChange({...value,port:Number(event.target.value),target_id:null})}/></FormField><FormField label="Calling AE" htmlFor={`${service}-calling`}><TextInput id={`${service}-calling`} className="mono" maxLength={16} required value={value.calling_ae} onChange={event=>onChange({...value,calling_ae:event.target.value.toUpperCase()})}/></FormField><FormField label="Called AE" htmlFor={`${service}-called`}><TextInput id={`${service}-called`} className="mono" maxLength={16} required value={value.called_ae} onChange={event=>onChange({...value,called_ae:event.target.value.toUpperCase(),target_id:null})}/></FormField></div>
}
