import {QueryClient,QueryClientProvider} from '@tanstack/react-query'
import {render,screen,waitFor} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import {MemoryRouter} from 'react-router-dom'
import {afterEach} from 'vitest'
import {api,Area,DicomEndpoint,DicomSystem,ModalityCheckResult,ModalityProfile,Site} from '../api/client'
import {Modalities} from '../pages/Modalities'

const site:Site={id:1,name:'Klinikum Nord',created_at:'',updated_at:''}
const area:Area={id:2,site_id:1,name:'Radiologie',created_at:'',updated_at:''}
const system:DicomSystem={id:3,name:'RIS/PACS Nord',created_at:'',updated_at:''}
const mwl:DicomEndpoint={id:7,system_id:3,name:'RIS MWL',service:'MWL',host:'ris.local',port:104,called_ae:'RIS',created_at:'',updated_at:''}
const store:DicomEndpoint={id:6,system_id:3,name:'PACS Store',service:'STORE',host:'pacs.local',port:11112,called_ae:'PACS',created_at:'',updated_at:''}
const profile:ModalityProfile={id:4,name:'Aplio 300 – Sono 2',description:'Sono Raum 2',modality:'US',calling_ae:'APLIO02',mwl_enabled:true,mwl_target_id:null,store_enabled:true,store_target_id:null,area_id:2,worklist_channel_id:5,store_endpoint_id:6,mwl_endpoint_id:7,station_ae_mode:'profile',station_ae_fixed_value:null,modality_filter_mode:'profile',modality_filter_fixed_value:null,created_at:'',updated_at:''}
const success:ModalityCheckResult={success:true,status:'PASS',duration_ms:42,overall:'success',profile_id:4,profile_name:profile.name,modality:'US',calling_ae:'APLIO02',run_id:10,worklist:{success:true,status:'0x0000',duration_ms:18,count:14,association:true,query:{station_ae:'APLIO02'}},store:{success:true,status:'0x0000',duration_ms:24,association:true,sop_class:'Ultrasound Image Storage',transfer_syntax:'Explicit VR Little Endian'}}

function setup(profiles:ModalityProfile[]=[profile],options:{areas?:Area[];endpoints?:DicomEndpoint[]}={}){vi.spyOn(api,'modalityProfiles').mockResolvedValue(profiles);vi.spyOn(api,'sites').mockResolvedValue([site]);vi.spyOn(api,'areas').mockResolvedValue(options.areas??[area]);vi.spyOn(api,'dicomSystems').mockResolvedValue([system]);vi.spyOn(api,'dicomEndpoints').mockResolvedValue(options.endpoints??[mwl,store]);const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return render(<QueryClientProvider client={client}><MemoryRouter><Modalities/></MemoryRouter></QueryClientProvider>)}
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals()})

it('summarizes direct Worklist and Store destinations',async()=>{setup();expect(await screen.findByText(profile.name)).toBeVisible();expect(screen.getByText(/RIS\/PACS Nord · RIS MWL/)).toBeVisible();expect(screen.getByText(/RIS\/PACS Nord · PACS Store/)).toBeVisible();expect(screen.queryByText(/Worklist-Kanal/)).not.toBeInTheDocument()})

it('creates an inline modality profile with direct endpoint and filters',async()=>{const create=vi.spyOn(api,'createInlineModalityProfile').mockResolvedValue(profile);setup([]);await userEvent.click(await screen.findByRole('button',{name:'Neue Modalität'}));await userEvent.type(screen.getByLabelText('Name'),'Aplio 300');await userEvent.selectOptions(screen.getByLabelText('Modalität'),'US');await userEvent.clear(screen.getByLabelText('Calling AE'));await userEvent.type(screen.getByLabelText('Calling AE'),'aplio02');await userEvent.selectOptions(screen.getByLabelText('Standort / Bereich'),'2');await userEvent.selectOptions(screen.getByLabelText('MWL-Endpoint'),'7');await userEvent.selectOptions(screen.getByLabelText('Modalitätsfilter'),'fixed');await userEvent.selectOptions(screen.getByLabelText('Modalitätswert'),'US');await userEvent.selectOptions(screen.getByLabelText('STORE-Endpoint'),'6');await userEvent.click(screen.getByRole('button',{name:'Speichern'}));await waitFor(()=>expect(create).toHaveBeenCalledWith(expect.objectContaining({calling_ae:'APLIO02',area_id:2,mwl_endpoint_id:7,modality_filter_mode:'fixed',modality_filter_fixed_value:'US',store_endpoint_id:6})))})

it('labels endpoint choices with system, endpoint, address and Called AE',async()=>{setup([]);await userEvent.click(await screen.findByRole('button',{name:'Neue Modalität'}));expect(screen.getByRole('option',{name:'RIS/PACS Nord · RIS MWL · ris.local:104 · Called AE RIS'})).toBeVisible();expect(screen.getByRole('option',{name:'RIS/PACS Nord · PACS Store · pacs.local:11112 · Called AE PACS'})).toBeVisible()})

it('edits resolved MWL settings inline',async()=>{const resolved={...profile,station_ae_mode:'fixed' as const,station_ae_fixed_value:'US_ROOM',modality_filter_mode:'fixed' as const,modality_filter_fixed_value:'US'};const update=vi.spyOn(api,'updateInlineModalityProfile').mockResolvedValue(resolved);setup([resolved]);await userEvent.click(await screen.findByRole('button',{name:'Bearbeiten'}));expect(screen.getByLabelText('MWL-Endpoint')).toHaveValue('7');expect(screen.getByLabelText('Station-AE-Filter')).toHaveValue('fixed');expect(screen.getByLabelText('Station-AE-Wert')).toHaveValue('US_ROOM');expect(screen.getByLabelText('Modalitätsfilter')).toHaveValue('fixed');expect(screen.getByLabelText('Modalitätswert')).toHaveValue('US');await userEvent.click(screen.getByRole('button',{name:'Speichern'}));await waitFor(()=>expect(update).toHaveBeenCalledWith(4,expect.objectContaining({mwl_endpoint_id:7,station_ae_mode:'fixed',station_ae_fixed_value:'US_ROOM'})))})

it('conditionally requires and disables direct service controls',async()=>{setup([]);await userEvent.click(await screen.findByRole('button',{name:'Neue Modalität'}));expect(screen.getByLabelText('MWL-Endpoint')).toBeRequired();expect(screen.getByLabelText('STORE-Endpoint')).toBeRequired();await userEvent.selectOptions(screen.getByLabelText('Station-AE-Filter'),'fixed');expect(screen.getByLabelText('Station-AE-Wert')).toBeRequired();await userEvent.click(screen.getByLabelText('MWL aktiviert'));expect(screen.getByLabelText('MWL-Endpoint')).toBeDisabled();expect(screen.getByLabelText('Station-AE-Filter')).toBeDisabled();expect(screen.queryByLabelText('Station-AE-Wert')).not.toBeInTheDocument()})

it.each([['MWL',{...profile,store_enabled:false,store_endpoint_id:null}],['STORE',{...profile,mwl_enabled:false,mwl_endpoint_id:null,worklist_channel_id:null}]])('supports a %s-only profile',async(_kind,value)=>{setup([value as ModalityProfile]);expect(await screen.findByRole('button',{name:'Modalität prüfen'})).toBeEnabled();expect(screen.getByText('Deaktiviert')).toBeVisible()})

it('keeps legacy profiles understandable and editable without forcing conversion',async()=>{const legacy={...profile,mwl_target_id:12,mwl_endpoint_id:null,worklist_channel_id:null,store_enabled:false,store_endpoint_id:null};const update=vi.spyOn(api,'updateInlineModalityProfile').mockResolvedValue(legacy);setup([legacy]);expect(await screen.findByText('Legacy-Ziel')).toBeVisible();await userEvent.click(screen.getByRole('button',{name:'Bearbeiten'}));expect(screen.getByText('Legacy-Konfiguration')).toBeVisible();expect(screen.getByLabelText('MWL-Endpoint')).toBeDisabled();await userEvent.click(screen.getByRole('button',{name:'Speichern'}));await waitFor(()=>expect(update).toHaveBeenCalledWith(4,expect.objectContaining({mwl_target_id:12})))})

it.each([
 ['MWL',{...profile,mwl_target_id:12,mwl_endpoint_id:null,worklist_channel_id:null}],
 ['STORE',{...profile,store_target_id:13,store_endpoint_id:null}],
])('only locks the legacy %s service while the structured service stays editable',async(kind,value)=>{const update=vi.spyOn(api,'updateInlineModalityProfile').mockResolvedValue(value as ModalityProfile);setup([value as ModalityProfile]);await userEvent.click(await screen.findByRole('button',{name:'Bearbeiten'}));const mwlSelect=screen.getByLabelText('MWL-Endpoint');const storeSelect=screen.getByLabelText('STORE-Endpoint');if(kind==='MWL'){expect(mwlSelect).toBeDisabled();expect(storeSelect).toBeEnabled();await userEvent.selectOptions(storeSelect,'6')}else{expect(mwlSelect).toBeEnabled();expect(storeSelect).toBeDisabled();await userEvent.selectOptions(mwlSelect,'7')}await userEvent.click(screen.getByRole('button',{name:'Speichern'}));await waitFor(()=>expect(update).toHaveBeenCalledWith(4,expect.objectContaining(kind==='MWL'?{mwl_target_id:12,store_endpoint_id:6}:{store_target_id:13,mwl_endpoint_id:7})))})

it('keeps unassigned profiles visible',async()=>{setup([{...profile,area_id:null}]);expect(await screen.findByRole('heading',{name:'Nicht zugeordnet'})).toBeVisible();expect(screen.getByText(profile.name)).toBeVisible()})

it('runs and renders a complete modality check',async()=>{vi.spyOn(api,'checkModalityProfile').mockResolvedValue(success);setup();await userEvent.click(await screen.findByRole('button',{name:'Modalität prüfen'}));expect(await screen.findByText('Overall PASS')).toBeVisible();expect(screen.getByText('14')).toBeVisible();expect(screen.getByText('Ultrasound Image Storage')).toBeVisible()})

it('runs broad zero-result diagnosis only after explicit action',async()=>{const zero={...success,worklist:{...success.worklist,count:0}};const check=vi.spyOn(api,'checkModalityProfile').mockResolvedValue(zero);setup();await userEvent.click(await screen.findByRole('button',{name:'Modalität prüfen'}));await userEvent.click(await screen.findByRole('button',{name:'Breite Worklist-Diagnose starten'}));await waitFor(()=>expect(check).toHaveBeenLastCalledWith(4,'explicit_vr_little_endian',expect.any(AbortSignal),true))})

it('edits and deletes a profile',async()=>{vi.spyOn(api,'updateInlineModalityProfile').mockResolvedValue(profile);const remove=vi.spyOn(api,'deleteModalityProfile').mockResolvedValue();vi.stubGlobal('confirm',()=>true);setup();await userEvent.click(await screen.findByRole('button',{name:'Bearbeiten'}));await userEvent.click(screen.getByRole('button',{name:'Speichern'}));await waitFor(()=>expect(api.updateInlineModalityProfile).toHaveBeenCalled());await userEvent.click(screen.getByRole('button',{name:`${profile.name} löschen`}));await waitFor(()=>expect(remove.mock.calls[0][0]).toBe(4))})

it('shows loading and technical details for a modality check',async()=>{let resolve:(value:ModalityCheckResult)=>void=()=>{};const pending=new Promise<ModalityCheckResult>(done=>{resolve=done});vi.spyOn(api,'checkModalityProfile').mockReturnValue(pending);setup();await userEvent.click(await screen.findByRole('button',{name:'Modalität prüfen'}));expect(screen.getByText('Worklist und PACS Store werden nacheinander getestet …')).toBeVisible();resolve(success);expect(await screen.findByText('Overall PASS')).toBeVisible();await userEvent.click(screen.getByText('Technische Details'));expect(screen.getByText(/"profile_id": 4/)).toBeVisible()})

it('cancels the browser wait and can retry the last check',async()=>{const check=vi.spyOn(api,'checkModalityProfile').mockImplementation((_id,_syntax,signal)=>new Promise((resolve,reject)=>{signal?.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError')));if(check.mock.calls.length>1)resolve(success)}));setup();await userEvent.click(await screen.findByRole('button',{name:'Modalität prüfen'}));await userEvent.click(screen.getByRole('button',{name:'Anzeige abbrechen'}));expect(await screen.findByText('Anzeige abgebrochen')).toBeVisible();await userEvent.click(screen.getByRole('button',{name:'Modalität prüfen'}));expect(await screen.findByText('Overall PASS')).toBeVisible();await userEvent.click(screen.getByRole('button',{name:'Erneut prüfen'}));await waitFor(()=>expect(check).toHaveBeenCalledTimes(3))})

it('blocks checks when an enabled direct endpoint is missing',async()=>{setup([{...profile,mwl_endpoint_id:null,worklist_channel_id:null}]);expect(await screen.findByText('Konfiguration unvollständig')).toBeVisible();expect(screen.getByRole('button',{name:'Modalität prüfen'})).toBeDisabled()})

it.each([
 ['worklist',{...success,success:false,status:'FAIL',overall:'failure' as const,worklist:{success:false,code:'DICOM_C_FIND_FAILED',message:'C-FIND failed',duration_ms:12,association:true},store:success.store}],
 ['store',{...success,success:false,status:'FAIL',overall:'failure' as const,worklist:success.worklist,store:{success:false,code:'DICOM_STORE_FAILED',message:'C-STORE failed',recommendation:'PACS-Importlog prüfen.',duration_ms:12,association:true}}],
])('shows a partial %s failure separately from the successful service',async(_service,result)=>{vi.spyOn(api,'checkModalityProfile').mockResolvedValue(result as ModalityCheckResult);setup();await userEvent.click(await screen.findByRole('button',{name:'Modalität prüfen'}));expect(await screen.findByText('Overall FAIL')).toBeVisible();expect(screen.getAllByText((result as ModalityCheckResult).worklist.success?'DICOM_STORE_FAILED':'DICOM_C_FIND_FAILED').length).toBeGreaterThan(0);expect(screen.getAllByText('PASS').length).toBeGreaterThan(0);expect(screen.getAllByText('FAIL').length).toBeGreaterThan(0)})
